In [3]:
import numpy as np    
import time


Creating a multimensional array with numpy

In [4]:
a = np.array([[1,2,3], [4,5,6]])
print(a, a.shape)

[[1 2 3]
 [4 5 6]] (2, 3)


Accessing data from arrays (Indexing)

In [5]:
print(a[1][2])

6


In [ ]:
b = np.arange(50)
print(b[-5])

45


Creating subarrays (Slicing)

In [19]:
# array[start:stop:step]
print(b[5: 10: 2], b[45:], b[:10:2])

[5 7 9] [45 46 47 48 49] [0 2 4 6 8]


In [21]:
c = np.mean(b)
print(c)

24.5


Vector dot product vs scalar product

In [26]:
print(a, b)
a = np.array([1,2,3])
b = np.array([4,5,6])
print(f"Vector dot product: {np.dot(a, b)}")
print(f"Scalar product: {a * b}")

[1 2 3] [4 5 6]
Vector dot product: 32
Scalar product: [ 4 10 18]


A BIdimensional array is a Matrix!

In [27]:
m = np.array([[1,2,3], [4,5,6]])
print(f"Matrix shape: {m.shape}")

Matrix shape: (2, 3)


In [28]:
a = np.arange(6).reshape(-1, 3)  
print(a)

[[0 1 2]
 [3 4 5]]


Slicing matrices

In [32]:
b = a[:, 0: 2: 1]
print(f"first two elements: {b}")

first two elements: [[0 1]
 [3 4]]
